version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql  # Script SQL para inicialização
    ports:
      - "3306:3306"  # Mapeamento da porta do MySQL

  ecommerce_go-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/go/src/app
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local
